name: anotherapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.11
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  permission_handler: ^10.2.0
  flutter_test:
    sdk: flutter
  patrol: ^1.1.0

flutter:

  uses-material-design: true

patrol:
  app_name: anotherapp
  android:
    package_name: com.example.anotherapp
